In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [2]:
df = pd.read_csv("hiring.csv")

In [3]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

# Fill the null value with Zero

In [4]:
df['experience'] = df['experience'].fillna("zero")

# Change the word one to 1

In [7]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [18]:
mts = df['test_score(out of 10)'].mean()

7.857142857142857

# Replace the null value the mean value

In [22]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mts)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [23]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

# Assign the input to X and output to y

In [25]:
X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]

In [26]:
y = df[['salary($)']]

In [27]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
reg.coef_

array([[2827.63404314, 1912.93803053, 2196.9753141 ]])

In [30]:
reg.intercept_

array([17237.33031373])

In [31]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [ ]:
2   10  10 

# Now predict the salary

In [28]:
reg.predict([[2,10,10]])

array([[63991.7318464]])

In [ ]:
reg.coef_

In [9]:
reg.predict([[2,10,10]])

array([67985.30289339])

In [ ]:
 y = mx + b 
 'experience','test_score(out of 10)','interview_score

reg.predict([[2,10,10]])
= 2 (2922.26901502) + 10 (2221.30909959) + 10 (2147.48256637) + 14992.65144669314
= 'experience'*exp_slope, 'test_score(out of 10) * test_score_slope', 'interview_score(out of 10) *int_score_slope + intercept
= 5,844.53 + 22,213.09 + 21474.82 + 14992.65


In [12]:
d.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [15]:
reg.predict([[2,2,2]])

array([29574.77280865])

In [17]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [18]:
reg.intercept_

14992.65144669314