In [1]:
import pandas as  pd
data = pd.read_csv('Diabeticpreprocessing.csv')

In [2]:
data.columns

Index(['Unnamed: 0', 'preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi',
       'age', 'class'],
      dtype='object')

In [3]:
data = data.drop(['Unnamed: 0'], axis=1)

In [4]:
data.head(5)

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

# Prepare Your Data For Machine Learning

1. Rescale data.
2. Standardize data.
3. Normalize data.
4. Binarize data

 A difficulty is that different algorithms make different assumptions about your data and may require different transforms

# 1.Rescale Data


Rescale Data : regression and neural networks and algorithms that use distance measures like k-Nearest Neighbors

In [25]:
data
X = data.drop('class',axis='columns')
Y = data[['class']]

In [1]:
X

NameError: name 'X' is not defined

In [26]:
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)

In [27]:
scaler = MinMaxScaler(feature_range=(0, 1)) 

In [28]:
rescaledX = scaler.fit_transform(X)


In [35]:
rescaledX

array([[0.353, 0.744, 0.59 , ..., 0.501, 0.234, 0.483],
       [0.059, 0.427, 0.541, ..., 0.396, 0.117, 0.167],
       [0.471, 0.92 , 0.525, ..., 0.347, 0.254, 0.183],
       ...,
       [0.294, 0.608, 0.59 , ..., 0.39 , 0.071, 0.15 ],
       [0.059, 0.633, 0.492, ..., 0.449, 0.116, 0.433],
       [0.059, 0.467, 0.574, ..., 0.453, 0.101, 0.033]])

In [30]:
from numpy import set_printoptions
set_printoptions(precision=3)

In [20]:
print(rescaledX[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


# 2. Standardize Data


Standardize Data : with a mean of 0 and a standard deviation of 1

linear regression, logistic regression

In [23]:

from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 

D:\DataScience\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\DataScience\Anaconda\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [25]:
set_printoptions(precision=3) 
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


# 3.Normalization

In [27]:
from sklearn.preprocessing import Normalizer

In [28]:
scaler = Normalizer().fit(X) 
normalizedX = scaler.transform(X) # summarize transformed data set_printoptions(precision=3) print(normalizedX[0:5,:])

In [30]:
# summarize transformed data 
set_printoptions(precision=3) 
print(normalizedX[0:5,:])

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


In [31]:
#Normalizing in scikit-learn refers to rescaling each observation (row) to have a length of 1 

# 4.Binarize Data

All values above the threshold are marked 1 and all equal to or below are marked as 0.

In [32]:
from sklearn.preprocessing import Binarizer

In [33]:
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)
# summarize transformed data 
set_printoptions(precision=3) 
print(binaryX[0:5,:])

#It is also useful when feature engineering and you want to add new features that indicate something meaningful


[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


# Feature Selection For Machine 

# 1. Feature Selection


Feature selection is a process where you automatically select those features in your data that contribute most to the prediction variable or output in which you are interested. Having irrelevant features in your data can decrease the accuracy of many models, especially linear algorithms like linear and logistic regression. Three benefits of performing feature selection before modeling your data are:


# Univariate Selection

In [36]:
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2

In [37]:
# feature extraction 
test = SelectKBest(score_func=chi2, k=4) 
fit = test.fit(X, Y) # summarize scores 
set_printoptions(precision=3) 
print(fit.scores_) 
features = fit.transform(X) # summarize selected features
print(features[0:5,:])


[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]
[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]


In [39]:
#['preg', 'plas',      'pres', 'skin',  'test',    'mass',   'pedi', 'age', ]
#[ 111.52  1411.887   17.605   53.108   2175.565  127.669    5.393  181.304]

The Recursive Feature Elimination (or RFE) works by recursively removing attributes and building a model on those attributes that remain.

In [40]:
from sklearn.feature_selection import RFE 
from sklearn.linear_model import LogisticRegression 

In [41]:
model = LogisticRegression(solver='liblinear') 
rfe = RFE(model, 3) 
fit = rfe.fit(X, Y) 
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_) 
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 3
Selected Features: [ True False False False False  True  True False]
Feature Ranking: [1 2 3 5 6 1 1 4]


D:\DataScience\Anaconda\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# 3. Principal Component Analysis

Principal Component Analysis (or PCA) uses linear algebra to transform the dataset into a compressed form. Generally this is called a data reduction technique. A property of PCA is that you can choose the number of dimensions or principal components in the transformed result. In the example below, we use PCA and select 3 principal components

In [45]:
# feature extraction 
from sklearn.decomposition import PCA 
pca = PCA(n_components=3) 
fit = pca.fit(X) # summarize components 
 
print(fit.components_)


[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02
   5.372e-04 -3.565e-03]
 [-2.265e-02 -9.722e-01 -1.419e-01  5.786e-02  9.463e-02 -4.697e-02
  -8.168e-04 -1.402e-01]
 [-2.246e-02  1.434e-01 -9.225e-01 -3.070e-01  2.098e-02 -1.324e-01
  -6.400e-04 -1.255e-01]]


# 4.Feature Importance


In [46]:
from sklearn.ensemble import ExtraTreesClassifier 

In [48]:
# feature extraction 
model = ExtraTreesClassifier(n_estimators=100) 
model.fit(X, Y) 
print(model.feature_importances_)

D:\DataScience\Anaconda\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[0.109 0.237 0.099 0.082 0.076 0.142 0.117 0.138]
