# NUMPY 

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.1


# DIMENSION OF ARRAY

In [1]:
!pip install numpy

In [10]:
a = [1,2,3,4,5,6.7,'India',True]
#     0 1 2 3 4  5     

In [2]:
a = [1,2,3,4,5,6.7]
type(a)

list

In [7]:
a = [1,2,3,4,5,6.7]

In [6]:
type(a)

list

In [8]:
import numpy as np
array1 = np.array([1,2,3,4,5,6])

In [9]:
type(array1)

numpy.ndarray

In [11]:
array1

array([1, 2, 3, 4, 5, 6])

In [10]:
array1.shape

(6,)

In [19]:
array1
type

array([1, 2, 3, 4, 5, 6])

In [20]:
array1.shape

(6,)

In [7]:
type(a)

list

In [ ]:
a = 

In [6]:
type(a)

list

In [3]:
import numpy as np 
a = np.array([1,2,3,4,5,6]) 

In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b1 = ([1,2,3,4,5,6,'india'])

In [7]:
b1

[1, 2, 3, 4, 5, 6, 'india']

In [8]:
a.shape

(6,)

In [9]:
a.ndim

1

In [10]:
#(6,)

#First value is , second row is columns

In [13]:
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [14]:
array_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
array_b.shape

(2, 5)

# CONVERT LIST TO ARRAY

In [15]:
a = ([1,2,3,4,5,6])

In [39]:
import numpy as np
modifiedarray = np.array(a)

In [40]:
modifiedarray.shape

(6,)

# CONVERT ARRAY TO LIST

In [41]:
modifiedlist = modifiedarray.tolist()

In [42]:
modifiedlist

[1, 2, 3, 4, 5, 6]

In [43]:
type(modifiedlist)

list

In [14]:
# two rows and columns

In [16]:
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]


In [17]:
array_abc = np.array([seq_a,seq_b,seq_c])

In [18]:
array_abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
array_abc.shape

(3, 3)

In [138]:
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]
seq_d = [10,11,12]
array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [114]:
array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [115]:
array_abc

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [116]:
array_abc.shape

(4, 3)

In [117]:
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]
seq_d = [10.1,11.1,12.1]

In [118]:
array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [119]:
array_abc

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10.1, 11.1, 12.1]])

In [120]:
# 5 X 2

arra5 = np.array([[1,2],[3,4],[5,6],[6,7],[7,8]])

In [121]:
arra5.ndim

2

In [122]:
arra5.shape

(5, 2)

In [123]:
#Excercise

# Reshaping 

In [37]:
newarr = np.array([[1,2,3],[2,3,4]])

In [38]:
newarr.shape

(2, 3)

In [39]:
newarr.size
# number of elelments 

6

In [40]:
reshapedarray = newarr.reshape(3,2)

In [41]:
reshapedarray.shape

(3, 2)

In [42]:
reshapedarray

array([[1, 2],
       [3, 2],
       [3, 4]])

In [43]:
newarr = np.array([[1,2,3],[2,3,4]])

In [44]:
newarr.reshape(6,1)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [45]:
newarr.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [46]:
newarr.reshape(2,3)

array([[1, 2, 3],
       [2, 3, 4]])

In [47]:
list1 = ([1,2,3,4,5])
newarr1 = np.array(list1)
newarr1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

# RESHAPE

In [48]:
arr_1d = np.arange(6)


In [49]:
arr_1d


array([0, 1, 2, 3, 4, 5])

In [50]:
arr_1d.shape
# One dimensional Array

(6,)

# RESHAPING ONEDIMENSIONAL ARRAY TO TWO DIMENSIONAL ARRAY

In [51]:
arr_2d = arr_1d.reshape((2, 3))

In [52]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
arr_2d.ndim

2

# MEMORY SIZE OF LIST

In [5]:
import sys

In [6]:
x = 1

In [7]:
type(x)

int

In [8]:
sys.getsizeof(x)

28

In [10]:
print("size of x: " + str(sys.getsizeof(x)) + "bytes")

size of x: 28bytes


In [11]:
a = ([1,2,3,4,5,6])

In [12]:
sys.getsizeof(a)

112

In [15]:
sys.getsizeof(a)

112

In [13]:
print("size of x: " + str(sys.getsizeof(a)) + "bytes")

size of x: 112bytes


In [ ]:
a = ([1,2,3,4,5,6,7,8,9,10])

In [14]:
import sys

In [2]:
import sys

In [25]:
x =1
sys.getsizeof(x)

28

In [26]:
a = ([1,2,3,4,5,6])
sys.getsizeof(a)

112

In [6]:
print("Size of a: " + str(sys.getsizeof(a)) + "bytes") 

Size of a: 112bytes


# MEMORY SIZE OF ARRAY

In [17]:
seqa = [1,2,3]
seqb = [4,5,6]
seqc = [7,8,9]
seqd = [10,11,12]

In [19]:
import numpy as np
arrayabcd = np.array([seqa,seqb,seqc,seqd])

In [20]:
arrayabcd

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
arrayabcd.ndim

2

In [22]:
arrayabcd.shape

(4, 3)

In [23]:
arrayabcd.size

12

In [24]:
arrayabcd.itemsize

4

In [25]:
arrayabcd.size * arrayabcd.itemsize

48

In [28]:
print("bytes "+str(arrayabcd.size * arrayabcd.itemsize))

bytes 48


In [29]:
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
arrayabcd = np.array([seqa,seqb,seqc,seqd])

In [30]:
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
arrayabcd = np.array([seqa,seqb,seqc,seqd])

In [31]:
import numpy as np

In [34]:
a =([1,2,3,4,5])

In [35]:
a.__sizeof__()

80

# RESHAPING

In [37]:
arr1d = np.arange(6)

In [38]:
arr1d

array([0, 1, 2, 3, 4, 5])

In [39]:
arr1d.ndim

1

In [40]:
arr1d.shape

(6,)

In [44]:
array2d =arr1d.reshape((3,2))

In [45]:
array2d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
arr2d = arr1d.reshape((2,3))


In [47]:
arr2d

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
array2d =arr1d.reshape((3,2))

In [49]:
array2d =arr1d.reshape((3,-1))

In [52]:
array2d.shape

(3, 2)

In [61]:
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
arrayabcd = np.array([seqa,seqb,seqc,seqd])

In [62]:
arrayabcd.shape

(4, 4)

In [67]:
array2d =arrayabcd.reshape((16,1))

In [69]:
arrnew = arrayabcd.reshape((2,8))


In [70]:
arrnew

array([[ 1,  2,  3,  4,  4,  5,  6,  5],
       [ 7,  8,  9,  9, 10, 11, 12, 13]])

In [68]:
array2d

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 6],
       [ 5],
       [ 7],
       [ 8],
       [ 9],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [ ]:
RESHAPING 1 DATA TO 3 D DATA

In [72]:
arr1d_bigger = np.arange(24)

In [73]:
arr1d_bigger

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [74]:
arr3d1 = arr1d_bigger.reshape(3,2,4)

In [77]:
arr3d1 = arr1d_bigger.reshape(4,3,2)

In [75]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
array2d

array([[0, 1],
       [2, 3],
       [4, 5]])

# Inbuilt function for Memory Size Of List

In [7]:
a.__sizeof__()

88

In [8]:
print("Size of a: " + str(a.__sizeof__()) + "bytes")

Size of a: 88bytes


# MEMORY SIZE OF ARRAY

In [15]:
import numpy as np
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]
seq_d = [10.1,11.1,12.1]
array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [16]:
array_abc.size

12

In [12]:
array_abc.itemsize

8

In [17]:
print("%d bytes" % (array_abc.size * array_abc.itemsize))

96 bytes


# REFRESHING

# RESHAPING 2 DIMENSIONAL ARRAY TO ONE DIMENSIONAL ARRAY

In [54]:
arr_2d.reshape((6,))

array([0, 1, 2, 3, 4, 5])

In [29]:
arr_2d = arr_1d.reshape((2, 3))

In [30]:
# COmment

RESHAPEDMINUS1 = arr_2d.reshape(-1)

In [31]:
RESHAPEDMINUS1.shape

(6,)

In [33]:
arr_1d = np.arange(6)
arr_2d = arr_1d.reshape((2, 3))
#arr_2d.ravel()

In [34]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
#arr_2d.ravel()

In [37]:
import numpy as np
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]
seq_d = [10.1,11.1,12.1]
array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [38]:
array_abc.shape

(4, 3)

In [40]:
n= array_abc.ravel()

In [42]:
n

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10.1, 11.1,
       12.1])

In [73]:
arr_1d.reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [74]:
arr_1d = np.arange(6)
#arr_2d = arr_1d.reshape((2, 3))

#arr_1d.reshape((3, -1))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
#arr_1d

array([0, 1, 2, 3, 4, 5])

In [126]:
z = arr_1d.reshape((3, -1))

In [63]:
#RESHAPEDMINUS1.ndim

1

In [129]:
z

array([[0, 1],
       [2, 3],
       [4, 5]])

# RESHAPING 1 D ARRAY to 3 DMENTIONAL ARRAY

In [88]:
# Advantage

In [75]:
arr_1d_bigger = np.arange(24)

In [76]:
arr_1d_bigger

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
arra_3d1 = arr_1d_bigger.reshape(3,2,4)

In [86]:
arra_3d1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [87]:
reshapedarray[0]
reshapedarray[:,0]

array([1, 3, 3])

In [78]:
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
arrayabcd = np.array([seqa,seqb,seqc,seqd])

In [79]:
arrayabcd

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

In [80]:
arrayabcd[0]

array([1, 2, 3, 4])

In [87]:
arrayabcd[0:4]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

In [89]:
arrayabcd[1:4]

array([[ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

In [ ]:
arrayabcd[0]

In [ ]:
#1 % slice

In [90]:
#99 % slice clolumns

In [91]:
arrayabcd[:,0]

array([ 1,  4,  7, 10])

In [92]:
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
arrayabcd = np.array([seqa,seqb,seqc,seqd])

In [93]:
arrayabcd[:,0]

array([ 1,  4,  7, 10])

In [94]:
arrayabcd[:,0:3]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# NUMPY DATA TYPE

In [106]:
newarr = np.array([[1,2,3],[2,3,4,],dtype=int)

In [107]:
newarr.size

6

In [108]:
newarr.itemsize

4

In [109]:
Memory = newarr.size * newarr.itemsize

In [110]:
Memory

24

In [119]:
changed64 = newarr.astype(np.int8)

In [120]:
changed64.size * changed64.itemsize

6

In [113]:
type(changed64)

numpy.ndarray

In [ ]:
#Before and afer reshaping the size should be same

In [ ]:
#Numpy Reshaping and Indexing

In [140]:
seq_a = [1,2,3,4]
seq_b = [5,6,7,8]
seq_c = [9,10,11,12]
seq_d = [13,14,15,16]
array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [141]:
array_abc

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [142]:
array_abc

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [145]:
array_abc.reshape(16,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [148]:
array_abc.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [150]:
array_abc.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [178]:
array_abc[0], array_abc[1] , array_abc[2], array_abc[3]

(array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]))

In [179]:
array_abc[0], array_abc[1] , array_abc[2], array_abc[-1]

(array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]))

In [180]:
array_abc[-1] , array_abc[-1]

(array([13, 14, 15, 16]), array([13, 14, 15, 16]))

In [182]:
array_abc[:,0]

array([ 1,  5,  9, 13])

In [183]:
array_abc[:,1]

array([ 2,  6, 10, 14])

In [184]:
array_abc[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [189]:
array_abc[:,0:5]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [197]:
array_abc[0,0:4]

array([1, 2, 3, 4])

In [196]:
array_abc[0,0:4]

array([1, 2, 3, 4])

In [195]:
array_abc[0:4,0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
newarr = np.array([[1,2,3],[2,3,4]])

# NUMPY ARRAY DATA TYPE

In [45]:
newarr.dtype

dtype('int32')

In [46]:
newarr = np.array([[1,2,3],[2,3,4]],dtype=float)

In [47]:
newarr.dtype

dtype('float64')

In [48]:
newarr

array([[1., 2., 3.],
       [2., 3., 4.]])

In [57]:
newarr = np.array([[1,2,3],[2,3,4]],dtype=int)

In [58]:
print("%d bytes" % (newarr.size * newarr.itemsize))

24 bytes


In [62]:
y = newarr.astype(np.int32)

In [63]:
type(y)

numpy.ndarray

In [64]:
print("%d bytes" % (y.size * y.itemsize))

24 bytes


In [ ]:
Create ARRAY

In [123]:
arra_b = np.ones((3,2))

In [124]:
arra_b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [125]:
## Create Array
ar = np.ones((4,4))
ar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [127]:
ar.dtype

dtype('float64')

In [130]:
zz = np.full((3,3),8)

In [131]:
zz

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [133]:
np.random.random((3,4))

array([[0.661669  , 0.36426856, 0.78069817, 0.93062661],
       [0.4237035 , 0.54037672, 0.46445147, 0.91441476],
       [0.60066015, 0.51342753, 0.6382809 , 0.58451216]])

In [139]:
from random import random

In [140]:
random()

0.7633257945367761

In [141]:
from numpy.random import rand

In [160]:
from random import random
from random import seed
seed(1)

random()


0.13436424411240122

# MATHS in NUMPY

In [163]:
array_e = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [164]:
array_e

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [165]:
array_e.sum()

42

In [166]:
array_e.sum(axis=1)
# rows

array([ 6, 15, 21])

In [167]:
array_e.sum(axis = 0)


array([11, 14, 17])

In [168]:
array_e.max(axis = 0)


array([6, 7, 8])

# Geneate New Array

In [154]:
array_b = np.zeros((3,2))

# Pass the shape ( tuple shape)

In [212]:
array_b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [213]:
array_b = np.zeros((3,2),dtype=int)

In [214]:
array_b

array([[0, 0],
       [0, 0],
       [0, 0]])

In [90]:
array_c = np.ones((3,))

In [216]:
array_c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [219]:
array_d = np.full((3,3), 8)

In [218]:
array_d

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [224]:
array_d = np.random.random((3,4))

In [225]:
array_d

array([[0.50576308, 0.04704927, 0.13284157, 0.32434343],
       [0.60225811, 0.09914878, 0.89618368, 0.76990455],
       [0.33215347, 0.12103035, 0.72379777, 0.24205302]])

# Data type and Memeory size

In [65]:
array_a = np.array([32766,32767,32768],dtype=np.int16)

In [66]:
array_a

array([ 32766,  32767, -32768], dtype=int16)

In [67]:
print(array_a.dtype)

int16


In [68]:
array_a

array([ 32766,  32767, -32768], dtype=int16)

In [69]:
array_c = np.array([32766,32767,32768])

In [70]:
array_c.dtype

dtype('int32')

# Change the dtype=int32

In [71]:
array_c = np.array([32766,32767,32768],dtype=np.int32)

In [72]:
array_c

array([32766, 32767, 32768])

# ARRAY MATHS

In [73]:
array_e = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [74]:
array_e.shape

(3, 3)

In [75]:
array_e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
array_e.sum()

45

In [77]:
array_e.sum(axis=1)

# axis 1 = row

array([ 6, 15, 24])

In [78]:
array_e.sum(axis=0)

# axis 0 =  column

array([12, 15, 18])

In [79]:
array_e.ptp(axis=1)

# [[1,2,3],[4,5,6],[7,8,9]])
# 3-1 ; 6-2 ; 9 -7

array([2, 2, 2])

In [80]:
array_e.min()

1

In [81]:
array_e.max()

9

In [82]:
array_e.mean()

5.0

In [83]:
array_e.min(axis=1)

array([1, 4, 7])

In [84]:
array_e.max(axis=1)

array([3, 6, 9])

In [85]:
array_e.mean(axis=1)

array([2., 5., 8.])

In [86]:
array_e[0].sum()

6

# BroadCasting Numpy Operation

In [87]:
array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [88]:
array_b = np.array([0,1,2,3])

In [89]:
array_c = np.array([[1],[2],[3]])

In [90]:
array_a.shape

(3, 4)

In [91]:
array_b.shape

(4,)

In [92]:
array_c.shape

(3, 1)

In [93]:
array_d = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [94]:
array_a + array_d

array([[2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6]])

In [95]:
array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
array_c = np.array([[1],[2],[3]])
array_a + array_c

array([[2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6]])

In [96]:
array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
array_b = np.array([0,1,2,4])
array_a + array_b

array([[1, 2, 3, 5],
       [2, 3, 4, 6],
       [3, 4, 5, 7]])

In [97]:
array_a.shape

(3, 4)

In [98]:
array_b.shape

(4,)

# Generating Random Numebrs

In [99]:
import numpy as np
np.random.random() 

0.13603740987860857

In [112]:

# seed the pseudorandom number generator
#from random import seed
from random import random
# seed random number generator
seed(1)
# generate some random numbers
print(random())
# reset the seed



0.13436424411240122


In [116]:
from numpy.random import rand
print(rand(3))

[0.5673372  0.76904902 0.91425484]


In [117]:
print(rand(10))

[0.36896793 0.93549744 0.12828432 0.98411184 0.14539062 0.64294776
 0.01676317 0.31840426 0.19231776 0.0019182 ]


In [119]:
from numpy.random import randint
values = randint(0, 10, 20)
print(values)

[5 9 0 0 6 4 5 5 0 7 4 1 4 3 7 0 6 8 4 3]


In [113]:
array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [117]:
array_a + array_a

array([[2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6]])

In [122]:
array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [119]:
array_a - array_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [121]:
array_a * array_a

array([[1, 1, 1, 1],
       [4, 4, 4, 4],
       [9, 9, 9, 9]])

In [123]:
array_a / array_a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])